### ISSUE TITLE
FlutterSegmentPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by danielgomezrico** [la-haus/flutter-segment#32] opened 2022-06-09 15:49 UTC
We have a deprecated implementation for the plugin on android:

There's a warning running the project:
```dart
android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java uses or overrides a deprecated API.
```

**Comment by vbuberen** [comment] 2022-06-09 19:07
This is caused by https://github.com/la-haus/flutter-segment/blob/master/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java#L97 since `middleware()` is deprecated and should be replaced with `useSourceMiddleware()`

<img width="636" alt="Screenshot 2022-06-09 at 22 06 52" src="https://user-images.githubusercontent.com/13467769/172925025-751caba8-2d8e-45fe-9dd6-49f36ec7a592.png">

**Comment by ariefwijaya** [comment] 2022-06-10 03:03
@vbuberen could you create a PR for it?

**Comment by vbuberen** [comment] 2022-06-10 06:34
Yes, that is the plan. Waited for Android updates PR to be merged first.

**Comment by vbuberen** [comment] 2022-06-10 06:46
Looked once again and found more of deprecated things - method from Flutter V1 embedding, which is not used anymore. 
https://github.com/la-haus/flutter-segment/blob/master/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java#L42

We were removing such things from Plus Plugins last November as well. Will also address it in my PR.

**Closed as completed** 2022-07-26 16:48 UTC
Labels: help wanted, platform-android
