### ISSUE TITLE
App installed event tracking problem for iOS

### ISSUE THREAD

**Issue by Mik77o** [la-haus/flutter-segment#26] opened 2022-05-05 08:24 UTC
I have noticed a problem with _app installed_ event not being tracked for iOS. I am using version `3.7.0`. In the Segment configuration `Segment.config` I have `trackApplicationLifecycleEvents set: true`, but this event does not seem to work.

**Comment by danielgomezrico** [comment] 2022-05-05 15:32
Are you talking about `Application Installed` event? 

https://segment.com/docs/connections/spec/mobile/#application-installed

**Comment by Mik77o** [comment] 2022-05-05 15:33
Yes :)

**Comment by Mik77o** [comment] 2022-05-05 15:37
On Android, this type of event is tracked. Maybe it's related to this: https://developer.apple.com/app-store/user-privacy-and-data-use/ 
Asking permissions to track

What do you think?

**Comment by Mik77o** [comment] 2022-05-10 07:35
@danielgomezrico, I tried to add tracking permissions via [app_tracking_transparency](https://pub.dev/packages/app_tracking_transparency) but still this event is not being tracked in the Segment.

**Comment by ariefwijaya** [comment] 2022-05-18 07:59
I don't think so, 
It is not because `this event is not being tracked in the Segment` , the event tracked by segment already, you can test it. 
I've tested it. 
![Untitled-1](https://user-images.githubusercontent.com/24664153/168987189-bd17f143-96a0-455f-b1ae-7f7319e1c331.png) 

As you can see, it was happened because in the default event like "Application Installed" never send fields `adTrackingEnabled` and `advertisingId`.  Refer to docs :
<img width="748" alt="image" src="https://user-images.githubusercontent.com/24664153/168987545-2dc549fc-f227-4069-8ac1-ed5e4d7ba3a9.png">

**Comment by ariefwijaya** [comment] 2022-05-18 08:15
Dunno why, it only happened in the `Application Installed` event. And not in another default event. For E.g 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/24664153/168991389-25b9ec20-1439-43cc-9e1d-cdfb910b0d94.png">

**Comment by danielgomezrico** [comment] 2022-05-18 10:50
I checked too for iOS and the events exists 🤔  

What else could be missing on your setup?

**Comment by ariefwijaya** [comment] 2022-05-18 11:16
@danielgomezrico Yes, the event exists, I think the problem is about IDFA. in some case such as facebook, the event will not received without IDFA

**Comment by Mik77o** [comment] 2022-05-26 09:00
@ariefwijaya, could you please include a snippet of code, what should the configuration look like in the Segment for Flutter app when using the [advertising_id](https://pub.dev/packages/advertising_id) and flutter_segment plugin? :)

**Comment by ariefwijaya** [comment] 2022-05-26 10:04
I prefer use facebook_app_events together with flutter_segment, so it will solve the problem without many boilerplate

**Comment by Mik77o** [comment] 2022-05-26 14:14
@ariefwijaya @danielgomezrico 
How was _advertisingId_ added manually? I added something like this on the Flutter side.
```
     SegmentDefaultOptions.instance.options = {
          'context': {
            'device': {
              'adTrackingEnabled': true,
              'advertisingId': advertisingId,
            }
          }
        };
```

Some of the fields for `device` field that were visible before are no longer present. It looks like the `device` part has been overwritten. Only the `type: ios` left.

From Segment:

before my changes

```
    "device": {
      "id": "test",
      "manufacturer": "test",
      "model": "test',
      "name": "test",
      "type": "ios"
    },
```

now (Adding a configuration manually)

```
    "device": {
      "adTrackingEnabled": true,
      "advertisingId": "00000000-0000-0000-0000-000000000000",
      "type": "ios"
    },
```

**Comment by ariefwijaya** [comment] 2022-05-26 15:31
Yes, but it won't delete any other value except the one we want to overwrite, So, it must be 
```
 "device": {
      "id": "test",
      "manufacturer": "test",
      "model": "test',
      "name": "test",
       "adTrackingEnabled": true,
      "advertisingId": "00000000-0000-0000-0000-000000000000",
      "type": "ios"
    },
  ```
  
  btw , I mix it with facebook_app_event plugin to track default event such as App Install

**Comment by zenled** [comment] 2022-06-01 12:39
Hey, I'm experiencing the same problem.
On Android, it all works as expected.
On iOS, the `Application Installed` event is not being triggered. (I have set `trackApplicationLifecycleEvents` to`true`)
The problem is probably in the way Segment is being configured:

If I configure Segment using Dart, by calling ` Segment.config(options: SegmentConfig(...` then the `Application Installed` event will not get triggered.

But If I configure Segment the deprecated way, by modifying the `Info.plist` then the `Application Installed` event will get triggered as expected.

In the [Segment documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#install-the-sdk) is says to configure Segment in the `application:didFinishLaunchingWithOptions`, this is the case when configuring via the `Info.plist`, but not when configuring with Dart.

**Comment by Mik77o** [comment] 2022-06-02 12:04
@danielgomezrico  @ariefwijaya I have a problem with `advertisingId` and `adTrackingEnabled ` fields in Segment for release mode (Android). It doesn't appear :/ 

I get the `advertisingId` from the [advertising_id](https://pub.dev/packages/advertising_id) package.

**Comment by ariefwijaya** [comment] 2022-06-10 02:59
@Mik77o for advertising id, this is how use it along flutter_segment. 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/24664153/172981396-16beaf83-4da8-4f4c-8711-0b3cf2c589f9.png">

you can use `.setContext` method to put any key-value pair under spesific preserved key. it won't delete any other value except the one we want to overwrite,

**Comment by ariefwijaya** [comment] 2022-06-10 03:01
...
> In the [Segment documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#install-the-sdk) is says to configure Segment in the `application:didFinishLaunchingWithOptions`, this is the case when configuring via the `Info.plist`, but not when configuring with Dart.

@danielgomezrico this happened to me, I found it never track Application Installed in iOS for our Dart-Installation. I've tried but now I have no idea to fix it,

**Comment by minoesteban** [comment] 2022-06-23 13:13
We are facing the same issue... after upgrading the package to 3.9.0 and removing the `Info.plist` keys not only we stopped getting `Application Installed` events but we are also not getting as many `Application Opened` events as we should. 

We are getting `Application Backgrounded` correctly though. 

So most times we get 4/5 `Application Backgrounded` events in a row from the same device, and not once we get `Application Opened`

By making the Dart `config` call conditional to all but `iOS` platform and adding back the `Info.plist` keys, we started getting the correct events frequency on iOS

Unfortunately I'm not proficient enough in iOS dev to figure out where is the issue, so I cannot offer any more assistance - I only got to conclude that `createConfigFromFile` and `createConfigFromDict` methods in `FlutterSegmentPlugin.m` look too similar to suspect an issue there 😅

**Comment by Mik77o** [comment] 2022-06-23 14:18
@minoesteban I think that Application Updated event is also not tracked. (for iOS)

**Comment by danielgomezrico** [comment] 2022-06-23 20:11
🤔 Its weird, I can see those events for iOS and android on our side, anyone has any clue?

**Comment by zenled** [comment] 2022-06-24 06:41
@danielgomezrico 
Can you confirm you are configuring Segment via Dart and not via `Info.plist`.

**Comment by b099l3** [comment] 2022-08-15 16:19
> Hey, I'm experiencing the same problem. On Android, it all works as expected. On iOS, the `Application Installed` event is not being triggered. (I have set `trackApplicationLifecycleEvents` to`true`) The problem is probably in the way Segment is being configured:
> 
> If I configure Segment using Dart, by calling ` Segment.config(options: SegmentConfig(...` then the `Application Installed` event will not get triggered.
> 
> But If I configure Segment the deprecated way, by modifying the `Info.plist` then the `Application Installed` event will get triggered as expected.
> 
> In the [Segment documentation](https://segment.com/docs/connections/sources/catalog/libraries/mobile/ios/#install-the-sdk) is says to configure Segment in the `application:didFinishLaunchingWithOptions`, this is the case when configuring via the `Info.plist`, but not when configuring with Dart.

This looks like it is a method sequence issue with when the dart method `Segment.config()` is called:

Method flow for App start with flutter-segment:

1. [AppDelegate](https://github.com/la-haus/flutter-segment/blob/master/example/ios/Runner/AppDelegate.m#L6) `didFinishLaunchingWithOptions:` 
2. [GeneratedPluginRegistrant](https://github.com/la-haus/flutter-segment/blob/master/ios/Classes/FlutterSegmentPlugin.m#L13) `registerWithRegistry:`
3. This is were the `info.plist` setup is called via [createConfigFromFile](https://github.com/la-haus/flutter-segment/blob/master/ios/Classes/FlutterSegmentPlugin.m#L19) and eventually [SEGAnalytics setupWithConfiguration](https://github.com/la-haus/flutter-segment/blob/master/ios/Classes/FlutterSegmentPlugin.m#L114) SEE **SEGAnalytics setupWithConfiguration** method flow BELOW
4. Then [AppDelegate](https://github.com/la-haus/flutter-segment/blob/master/example/ios/Runner/AppDelegate.m#L10) calls `super didFinishLaunchingWithOptions:`

For the dart Implementation calling `Segment.config()`:
1. Calls [SEGAnalytics setupWithConfiguration](https://github.com/segmentio/analytics-ios/blob/fc64997865619f73bbab196c164f7845a13da110/Segment/Classes/SEGAnalytics.m#L36) in the native library, SEE **SEGAnalytics setupWithConfiguration** method flow BELOW

### **SEGAnalytics setupWithConfiguration** method flow
1. Setups up [listeners to the native lifecycle events](https://github.com/segmentio/analytics-ios/blob/fc64997865619f73bbab196c164f7845a13da110/Segment/Classes/SEGAnalytics.m#L72)
1. Then when `didFinishLaunchingWithOptions` is called [sends the Application Installed event](https://github.com/segmentio/analytics-ios/blob/fc64997865619f73bbab196c164f7845a13da110/Segment/Classes/SEGAnalytics.m#L183)

So if you call `Segment.config()` after **AppDelegate** `didFinishLaunchingWithOptions:` you will miss the first event. The [setup instructions state](https://segment.com/docs/connections/sources/catalog/libraries/mobile/swift-ios/#getting-started) that this needs to be done in a lifecycle event, e.g., `didFinishLaunchingWithOptions`

I wonder if there is away to call `Segment.config()` in `didFinishLaunchingWithOptions`?

**Comment by b099l3** [comment] 2022-08-15 20:36
I created a potential fix, #56, that manually sends the event `Application Installed` and `Application Updated` when we call the dart code `Segment.config()`. 

This is in the native iOS code of flutter_segement so will only run on iOS. It works in the same way that the native segment package works, [analysis-ios](https://github.com/segmentio/analytics-ios), checks the same `NSUserDefaults`, the implementation details of that method is [here](https://github.com/segmentio/analytics-ios/blob/fc64997865619f73bbab196c164f7845a13da110/Segment/Classes/SEGAnalytics.m#L163).

Tested and is sending the events now.

**Comment by savy-91** [comment] 2022-08-30 09:04
Maybe this can be closed @danielgomezrico ?

**Comment by danielgomezrico** [comment] 2022-08-30 15:45
@Mik77o has updated to the latest version? This should be fixed after https://github.com/la-haus/flutter-segment/pull/56

**Comment by Mik77o** [comment] 2022-08-30 18:57
@danielgomezrico Thanks for reminder. I will check it soon :)

**Comment by danielgomezrico** [comment] 2022-09-15 19:07
@Mik77o any updates? 🤓

**Comment by Mik77o** [comment] 2022-10-26 08:53
@danielgomezrico Seems to be working now! :)

**Comment by danielgomezrico** [comment] 2022-10-26 15:49
You are welcome to reopen if it breaks again

**Closed as completed** 2022-10-26 15:49 UTC
Labels: help wanted
